### ISSUE TITLE
Actividad 2 conversaciones 

### ISSUE THREAD

**Issue by Johnc-byte** [SistemasTecTlaxiaco/actividad-2-ejercicios-1as-jonathan-cruz-cuevas#1]
[Actividad2_conversiones.pdf](https://github.com/user-attachments/files/16841770/Actividad2_conversiones.pdf)

**Comment by irwingsael** [comment]
portada: 25
Procedimiento:25
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 25
Calificación de la practica: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisadol...
