### ISSUE TITLE
Practica de Conjuntos

### ISSUE THREAD

**Issue by Johnc-byte** [SistemasTecTlaxiaco/actividad-2-ejercicios-1as-jonathan-cruz-cuevas#2]
[conjuntos_practica.pdf](https://github.com/user-attachments/files/17106919/conjuntos_practica.pdf)

**Comment by LenninGS-0** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 25/25
Resultados y conclusiones 25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
